# Selecting element

How to select any element in a Array or matrix. 

In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3,4,5,6,7,8,9])
print(v[0])


1


# Slicing 
Slicing in 1-D array

In [3]:
##  colon(:) used for starting and ending element.
v[:]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
v[3:6]

array([4, 5, 6])

In [5]:
v[-1]

9

# Slicing in a matrix

In [7]:
matrix = np.array([[15,20,45],[56,89,70],[32,12,54]])
print(matrix)

[[15 20 45]
 [56 89 70]
 [32 12 54]]


# comma(,) is used for slicing in the form of row and columns in a matrix.
[row,column]

In [8]:
matrix[0,0]

15

In [9]:
matrix[1,1]

89

In [10]:
matrix[2,2]

54

# slicing on rows

In [11]:
matrix [ :3, :2]

array([[15, 20],
       [56, 89],
       [32, 12]])

In [12]:
matrix[0:2, 0:1]

array([[15],
       [56]])

In [13]:
matrix[0:1, 0:1]

array([[15]])

In [14]:
print(matrix[:  , 0:])

[[15 20 45]
 [56 89 70]
 [32 12 54]]


In [15]:
print(matrix[1:2, 1:2])

[[89]]


In [16]:
print(matrix[:, 1:2])

[[20]
 [89]
 [12]]


In [17]:
print(matrix[: , 2:3])

[[45]
 [70]
 [54]]


In [18]:
matrix[: , 3:2]

array([], shape=(3, 0), dtype=int32)

In [21]:
# matrix with steps 

print(matrix[0:3:2 , 2:3:2])

[[45]
 [54]]


In [22]:
matrix[-3:-1, -3:-2]

array([[15],
       [56]])

In [23]:
matrix[-2:0:1, -2:0:1]

array([], shape=(0, 0), dtype=int32)

# Describe a Matrix

In [24]:
matrix = np.array([[15,20,45],[56,89,70],[32,12,54]])
print(matrix)

[[15 20 45]
 [56 89 70]
 [32 12 54]]


# some properties to describe a matrix

In [25]:
# parenthesis() not allow in this method and return values  in a tuple form.
matrix.shape

(3, 3)

In [26]:
# size - return numbers of values.
matrix.size

9

In [27]:
# ndim - how many dimension
matrix.ndim

2

# Find max and min values in a matrix

In [28]:
print(np.max(matrix))

89


In [29]:
print(np.min(matrix))

12


In [30]:
matrix

array([[15, 20, 45],
       [56, 89, 70],
       [32, 12, 54]])

In [31]:
# row and columns wise max values then use axis.
print(np.max(matrix, axis=1))

[45 89 54]


In [32]:
print(np.max(matrix, axis=0))

[56 89 70]


In [34]:
print(np.max(matrix, axis = 1)[2])

54


In [39]:
print(np.max(matrix, axis = 1)[1])

89


In [43]:
matrix[0,0],[1,1],[2,1]

(15, [1, 1], [2, 1])

# Basic matrix statistics - Mean, Variance, Standard deviation 

In [44]:
matrix

array([[15, 20, 45],
       [56, 89, 70],
       [32, 12, 54]])

In [45]:
print(np.mean(matrix))

43.666666666666664


In [46]:
print(np.var(matrix))

614.4444444444445


In [47]:
print(np.std(matrix))

24.78798992343761


# Reshaping Array


In [48]:
matrix

array([[15, 20, 45],
       [56, 89, 70],
       [32, 12, 54]])

In [49]:
print(matrix.reshape(9))

[15 20 45 56 89 70 32 12 54]


In [53]:
print(matrix.reshape(9,1))

[[15]
 [20]
 [45]
 [56]
 [89]
 [70]
 [32]
 [12]
 [54]]


In [57]:
print(matrix.reshape(1,-1))

[[15 20 45 56 89 70 32 12 54]]


In [ ]:
# flatten function - this function change any dimension in a single row. 

In [58]:
print(matrix.flatten())

[15 20 45 56 89 70 32 12 54]
