# NumPy
Full form = Numeric Python


In [1]:
! pip install numpy

# Creating Vector
NumPy work with Array.
Array = Array is a collection of siliar data types.
List  = List is a collection of different data types.


In [2]:
import numpy as np 

In [3]:
v = np.array([1,2,3,4,5,6,7,8,9])
print(v)

[1 2 3 4 5 6 7 8 9]


# multi dimension array

In [4]:
c  =np.array([[1],[2],[3]])
print(c)

[[1]
 [2]
 [3]]


# Creating a Matrix

In [5]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
