In [1]:
import numpy as np

In [2]:
array1 = np.array([[100,200,300,400],[500,600,700,800]])
print(array1)

[[100 200 300 400]
 [500 600 700 800]]


In [3]:
array2 = np.matrix('11 22; 33 44; 55 66')
print(array2)

[[11 22]
 [33 44]
 [55 66]]


In [5]:
newarray = np.array([10,20,30,40,50,60])
array3 = np.reshape(newarray,(3,2))

In [6]:
array3

array([[10, 20],
       [30, 40],
       [50, 60]])

In [7]:
array4 = np.zeros((4,2))

In [8]:
array4

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
array5 = np.ones((2,3))
print(array5)

[[1. 1. 1.]
 [1. 1. 1.]]
