In [1]:
import numpy as np

In [2]:
matrix = np.matrix([[51,87,14],[33,21,6],[9,78,88]])
print(matrix)

[[51 87 14]
 [33 21  6]
 [ 9 78 88]]


# Linear Algebra Operation perform on Matrix

# 1. Transpose of matrix

In [4]:
# Transpose of a Matrix
#swap all the value of row and columns without changing diagonal element.
print(matrix.T)

[[51 33  9]
 [87 21 78]
 [14  6 88]]


# 2. Determinant and Rank

In [5]:
matrix

matrix([[51, 87, 14],
        [33, 21,  6],
        [ 9, 78, 88]])

In [6]:
print(np.linalg.det(matrix))

-144180.00000000006


# 3. Rank of a matrix

In [7]:
print(np.linalg.matrix_rank(matrix))

3


# 4. Diagonal

In [11]:
matrix

matrix([[51, 87, 14],
        [33, 21,  6],
        [ 9, 78, 88]])

In [8]:
matrix.diagonal()

matrix([[51, 21, 88]])

In [ ]:
matrix.diagonal?

In [13]:
matrix.diagonal(offset = 1)

matrix([[87,  6]])

In [10]:
matrix.diagonal(offset = -1)

matrix([[33, 78]])

# 5. Trace

In [14]:
matrix

matrix([[51, 87, 14],
        [33, 21,  6],
        [ 9, 78, 88]])

In [15]:
# trace --> print the sum of diagonal values
matrix.trace()


matrix([[160]])

# 6. Dot product

In [16]:
matrix1 = np.matrix([[51,87,14],[33,21,6],[9,78,88]])
matrix2 = np.matrix([[51,87,14],[33,21,6],[9,78,88]])
print(matrix1)
print(matrix2)

[[51 87 14]
 [33 21  6]
 [ 9 78 88]]
[[51 87 14]
 [33 21  6]
 [ 9 78 88]]


In [17]:
print(np.dot(matrix1, matrix2))

[[5598 7356 2468]
 [2430 3780 1116]
 [3825 9285 8338]]


In [18]:
print(matrix1 * matrix2)

[[5598 7356 2468]
 [2430 3780 1116]
 [3825 9285 8338]]


In [19]:
print(np.add(matrix1, matrix2))

[[102 174  28]
 [ 66  42  12]
 [ 18 156 176]]


In [20]:
print(np.subtract(matrix1, matrix2))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# 7. Random values

In [22]:
np.random.randint(0,11,3)

array([ 6,  1, 10])

In [23]:
np.random.randint(0,11,9).reshape(3,3)

array([[ 8,  4,  6],
       [ 0,  7,  0],
       [ 3, 10,  2]])

In [25]:
np.random.seed(5)
np.random.randint(0,11,3)

array([3, 6, 6])

# 8. Normal distribution

In [26]:

#                mean  std total number
np.random.normal(1.0, 2.0, 10)

array([ 0.95339251,  2.68355533,  3.73517105,  2.14941538, -2.77152482,
        1.34185074,  0.19381338,  4.27525698, -0.2105957 , -2.18883015])

In [27]:
np.random.normal(5.0, 4.5, 5)

array([ 9.10343139, -1.49728699, 13.20998074, 11.55931306,  0.90383832])

In [28]:
np.random.normal(1.0, 2.0, 10).reshape(2,5)

array([[-0.98003789, -0.63509625, -1.33655895,  0.57844071,  0.55140067],
       [ 2.30245691, -0.92552397,  5.47748589,  1.49557076,  1.65279226]])