# Program for creating arrays using different functions.

In [1]:
import numpy as np

In [3]:
myarray = np.arange(15)
print(myarray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# creating float array using arange() function

In [6]:
myarray1 = np.arange(14,19, dtype = np.float)
print(myarray1)

[14. 15. 16. 17. 18.]


C:\Users\RUCHIK~1\AppData\Local\Temp/ipykernel_6364/189148653.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  myarray1 = np.arange(14,19, dtype = np.float)


# Creating an integer array using linspace() for equal spacing

In [8]:
myarray2 = np.linspace(12,24,5)
print(myarray2)

[12. 15. 18. 21. 24.]


# Creating float array using linspace() for equal spacing.

In [9]:
myarray3 = np.linspace(1. ,  4. ,  5)
print(myarray3)

[1.   1.75 2.5  3.25 4.  ]


# Creating array using Zeros() function.

In [10]:
myarray4 = np.zeros((4))
print(myarray4)

[0. 0. 0. 0.]


# Creating array using ones() function.

In [11]:
myarray5 = np.ones((10))
print(myarray5)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
